#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Pull Stored Data
      shell: 'cat /tmp/watchtower.set'
      register: programs

    - name: Deploy watchtower
      docker_container:
        name: 'watchtower'
        image: 'containrrr/watchtower'
        pull: yes
        command: '{{programs.stdout}} --cleanup --interval 600'
        state: started
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
        restart_policy: unless-stopped
        networks:
          - name: psautomate
            aliases:
              - 'watchtower'
