#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705 - Deiteq
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
source /psa/stage/functions/sudocheck.sh
source /psa/stage/functions/restorecheck.sh
source /psa/stage/version/file.sh

sudocheck
restorecheck
mainstart
