#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705 - Deiteq - Sub7Seven
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
echo ""
echo "-----------------------------------------------------"
echo "SYSTEM MESSAGE: Please Copy Your Information"
echo "-----------------------------------------------------"
echo ""
cat /psa/var/vpn.info
echo ""
echo "Config Info: Visit http://psavpn.psautomate.io or WIKI"
